agent:
  name: face_recognition
  description: >
    Agent to perform face detection and recognition, predicted face embeddings
    are compared against face embeddings stored in gallery file.

templates:
- template_name: InputTemplate-1
  class_name: InputTemplate
  attributes: {}

- template_name: RetinaFacePytorch-1
  class_name: RetinaFacePytorchTRT
  template_input: InputTemplate-1
  attributes:
    return_key_points: true
    confidence_threshold: 0.3
    local_model_path: "/root/.cache/torch/hub/checkpoints/resnet50_2020-07-20.engine"

- template_name: PytorchEmbeddingSearch-1
  class_name: PytorchEmbeddingSearch
  template_input: RetinaFacePytorch-1
  attributes:
    k_value: 3
    gallery_file: artifacts/gallery_files/lfw_gallery.gallery
    metric: cosine
    similarity_threshold: 0.5
    image_root_dir:  /opt/app/dataset
    model_kwargs:
      metadata:
        template_instance_name: PytorchEmbeddingSearch-1
        agent_name: face_recognition

- template_name: BBoxDrawer
  class_name: BBoxDrawer
  template_input: PytorchEmbeddingSearch-1
  attributes:
    draw_boxes: true
    draw_key_points: true
    randomized_color: false