name: sinapsis-retina-face-trt

services:
  sinapsis-retina-face-trt-main:
    image: sinapsis-retina-face-trt:base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      ssh:
        - default
    shm_size: '8gb'
    environment:
      PYTHONPATH: /lib/python3.10/:/app/.venv/lib/python3.10/site-packages
      AGENT_CONFIG_PATH: "src/sinapsis_retina_face_trt/configs/face_recognition.yml"
      GRADIO_SHARE_APP: ${GRADIO_SHARE_APP:-false}
      PYTHONUNBUFFERED: 1
    volumes:
      - "~/.deepface/weights:/root/.deepface/weights"
      - "~/.cache/torch:/root/.cache/torch"
      - "~/.cache/sinapsis/:/root/.cache/sinapsis"
      - "../webapps/:/app/webapps"
      - "../src/sinapsis_retina_face_trt/configs/:/app/src/sinapsis_retina_face_trt/configs/"

    network_mode: "host"
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

