FROM sinapsis-nvidia:base

RUN mkdir -p /root/.deepface/weights

COPY . /app/
WORKDIR /app
RUN uv build
RUN uv sync --frozen

RUN uv pip install /app/dist/sinapsis_retina_face_trt-0.1.0-py3-none-any.whl[all]
RUN uv pip install tensorflow[and-cuda]==2.18.0
